<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Ваш личный кабинет</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <section>
            <header>Ваш кабинет</header>
        </section>
        <section>
            <p>Чтобы мы могли присылать подходящие вам опросы, пожалуйста, <a href="http://www.surveygizmo.com/s3/1884090/screening?user_id=1&survey_id=1">ответьте на несколько вопросов.</a></p>
        </section>
        <section>
            <header>Доступные опросы:</header>
            <article>
                <div>К сожалению, сейчас нет опросов для вас. Заходите позже.</div>
            </article>
        </section>
    </body>
</html>
