<!doctype html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>Панель - вход</title>
    <link href="/css/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap/bootstrap-theme.min.css" rel="stylesheet">
    <link href="/css/custom.css" rel="stylesheet">
    <script src="/js/jquery/jquery-1.11.0.min.js"></script>
</head>
<body>
<table style="height: 100%; width: 100%;">
    <tr><td>
            <form id="formLogin" action="<?= $form->getAction(); ?>" method="POST">
                <div class="panel panel-default col-md-4 col-md-offset-4">
                    <div class="panel-heading">
                        <h3 class="panel-title">Вход</h3>
                    </div>
                    <div class="panel-body">
                        <?php if($nf){ ?>
                                    <?php $this->flash->notice("Пользователь с такими данными не существует"); ?>
                        <?php }?>
                        <?php if($err){ ?>
                                    <?php $this->flash->notice("Были введены некорректные данные"); ?>
                        <?php }?>
                        <div class="form-group">
                            <p>
                                <label for="txtEmail">E-mail:</label>
                                <?= $form->render('email',array('class'=>'form-control')); ?>
                            </p>
                        </div>
                        <div class="form-group">
                            <p>
                                <label for="txtPassword">Пароль:</label>
                                <?= $form->render('password',array('class'=>'form-control')); ?>
                            </p>
                        </div>
                        <div class="form-buttons-group">
                            <?= $form->render('submit',array('class'=>'btn btn-primary col-md-3')); ?>
                            <input type="button" id="reg_btn" class="btn btn-default col-md-3" value="Регистрация" />
                        </div>
                    </div>
                </div>
            </form>
        </td></tr>
</table>
<script type="text/javascript">
    $(document).ready(function() {
        $('input#reg_btn').click(function(){
            window.location = '/registration';
        });
    });
</script>
</body>
</html>